In [4]:
import pandas as pd
import numpy  as np

In [5]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [6]:
train=pd.read_csv('C:\\Users\\Edosomwan Oghogho\\Desktop\\first semester doc\\churn_myBB.csv')

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 7 columns):
intPlan          3333 non-null object
vmailPlan        3333 non-null object
intMin           3333 non-null float64
intCalls         3333 non-null int64
intCharges       3333 non-null float64
custServCalls    3333 non-null int64
churn            3333 non-null object
dtypes: float64(2), int64(2), object(3)
memory usage: 182.4+ KB


In [8]:
train.head()

intPlan vmailPlan  intMin  intCalls  intCharges  custServCalls   churn
0      no       yes    10.0         3        2.70              1  False.
1      no       yes    13.7         3        3.70              1  False.
2      no        no    12.2         5        3.29              0  False.
3     yes        no     6.6         7        1.78              2  False.
4     yes        no    10.1         3        2.73              3  False.

In [9]:
train.describe()

intMin     intCalls   intCharges  custServCalls
count  3333.000000  3333.000000  3333.000000    3333.000000
mean     10.237294     4.479448     2.764581       1.562856
std       2.791840     2.461214     0.753773       1.315491
min       0.000000     0.000000     0.000000       0.000000
25%       8.500000     3.000000     2.300000       1.000000
50%      10.300000     4.000000     2.780000       1.000000
75%      12.100000     6.000000     3.270000       2.000000
max      20.000000    20.000000     5.400000       9.000000

In [10]:
vmail= 'Yes'
train['vmailPlan'].replace('yes', vmail, inplace=True)

In [11]:
# Making the variables binary for columns with yes/no. yes=1 and no=0

IntPlan= pd.get_dummies(train['intPlan'],drop_first=True)
# However,we cannot use both categories that is;yes or no.
#Doing so would give the regression redundant information, result in multicollinearity, and break the model. 
#This means we have to leave one category out, and we call this missing category the reference category. (drop_first=True)
#Using the reference category makes all interpretation in reference to that category

In [12]:
VmailPlan= pd.get_dummies(train['vmailPlan'],drop_first=True)

In [13]:
Churn= pd.get_dummies(train['churn'],drop_first=True)

In [14]:
train=pd.concat([train,IntPlan,VmailPlan,Churn],axis=1)

In [15]:
train.head()

intPlan vmailPlan  intMin  intCalls  intCharges  custServCalls   churn  yes  \
0      no       Yes    10.0         3        2.70              1  False.    0   
1      no       Yes    13.7         3        3.70              1  False.    0   
2      no        no    12.2         5        3.29              0  False.    0   
3     yes        no     6.6         7        1.78              2  False.    1   
4     yes        no    10.1         3        2.73              3  False.    1   

   no  True.  
0   0      0  
1   0      0  
2   1      0  
3   1      0  
4   1      0

In [16]:
#drop the variables
train.drop(['intPlan','vmailPlan','churn'],axis=1, inplace=True)

In [17]:
train.rename(columns = {'yes': 'IntPlan', 'no': 'VmailPlan', 'True.':'Churn'}, inplace=True)

In [18]:
train.head()

intMin  intCalls  intCharges  custServCalls  IntPlan  VmailPlan  Churn
0    10.0         3        2.70              1        0          0      0
1    13.7         3        3.70              1        0          0      0
2    12.2         5        3.29              0        0          1      0
3     6.6         7        1.78              2        1          1      0
4    10.1         3        2.73              3        1          1      0

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
train.columns

Index(['intMin', 'intCalls', 'intCharges', 'custServCalls', 'IntPlan',
       'VmailPlan', 'Churn'],
      dtype='object')

In [21]:
x=train[['intMin', 'intCalls', 'intCharges', 'custServCalls', 'IntPlan',
       'VmailPlan']]
y=train['Churn']

In [22]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [23]:
from sklearn.tree import DecisionTreeClassifier

In [24]:
dtree = DecisionTreeClassifier()

In [25]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [26]:
predictions = dtree.predict(X_test)

In [27]:
from sklearn.metrics import classification_report,confusion_matrix

In [28]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.89      0.90      0.90       857
           1       0.35      0.31      0.33       143

   micro avg       0.82      0.82      0.82      1000
   macro avg       0.62      0.61      0.61      1000
weighted avg       0.81      0.82      0.81      1000



In [29]:
print(confusion_matrix(y_test,predictions))

[[774  83]
 [ 98  45]]


In [30]:
dtree.feature_importances_

array([0.19802304, 0.23453599, 0.29334638, 0.16679935, 0.08945572,
       0.01783953])

In [31]:
from sklearn.metrics import confusion_matrix
from sklearn import metrics

In [32]:
print("Accuracy:",metrics.accuracy_score(y_test, predictions))
print("Precision:",metrics.precision_score(y_test, predictions))
print("Recall:",metrics.recall_score(y_test, predictions))

Accuracy: 0.819
Precision: 0.3515625
Recall: 0.3146853146853147


# RANDOM FOREST

In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
rfc = RandomForestClassifier(n_estimators=600) 

In [36]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=600, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [37]:
prediction = rfc.predict(X_test)

In [38]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       0.89      0.96      0.92       857
           1       0.53      0.29      0.38       143

   micro avg       0.86      0.86      0.86      1000
   macro avg       0.71      0.62      0.65      1000
weighted avg       0.84      0.86      0.84      1000



In [39]:
print(confusion_matrix(y_test,prediction))

[[819  38]
 [101  42]]


In [40]:
rfc.feature_importances_

array([0.21877704, 0.21819654, 0.21940543, 0.19889857, 0.12269986,
       0.02202255])